options:
  logging: CLOUD_LOGGING_ONLY
  serviceAccount: projects/395010938272/serviceAccounts/general-service-account@opentofu-test-project.iam.gserviceaccount.com

steps:
  - name: "ghcr.io/opentofu/opentofu:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd infra/stacks/compute
        tofu init
        tofu destroy -auto-approve
        tofu apply -auto-approve

  - name: "ghcr.io/opentofu/opentofu:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd infra/stacks/disks
        tofu init
        tofu destroy -auto-approve
        tofu apply -auto-approve

  - name: "ghcr.io/opentofu/opentofu:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd infra/stacks/firestore
        tofu init
        tofu destroy -auto-approve
        tofu apply -auto-approve
