options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "ghcr.io/opentofu/opentofu:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd infra
        tofu init
        tofu apply -auto-approve
